version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb

  frontend:
    build: ./challengeAvati
    ports:
      - '5173:5173'
    volumes:
      - ./challengeAvati:/app
      - /app/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
